version: '3.9'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  wordpress_db:
  wordpress_files:

networks:
  inception_network:
