version: "3.8"

services:
    nginx:
        build: requirements/nginx
        container_name: nginx
        depends_on:
            - wordpress
            - mariadb
        ports:
            - "443:443"
        env_file:
            - .env
        volumes:
            - ${WEB_CONTENT_PATH}:/var/www/html
        networks:
            inception:
    wordpress:
        build: requirements/wordpress
        container_name: wp-php
        env_file:
            - .env
        depends_on:
            - mariadb
        volumes:
            - ${WEB_CONTENT_PATH}:/var/www/html
        networks:
            inception:
    mariadb:
        build: requirements/mariadb
        container_name: mariadb
        env_file:
            - .env
        volumes:
            - ${DB_DATA_PATH}:/var/lib/mysql
        networks:
            inception:
networks:
    inception:
