version: "3.8"

services:
    nginx:
        build: requirements/nginx
        image: nginx:jberay
        container_name: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        env_file:
            - .env
        volumes:
            - web_content:/var/www/html
        networks:
            - inception
        restart: always

    wordpress:
        build: requirements/wordpress
        image: wordpress:jberay
        container_name: wordpress
        ports:
            - "9000"
        env_file:
            - .env
        depends_on:
            - mariadb
        volumes:
            - web_content:/var/www/html
        networks:
            - inception
        restart: always

    mariadb:
        build: requirements/mariadb
        image: mariadb:jberay
        container_name: mariadb
        ports:
            - "3306"
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - inception
        restart: always
networks:
    inception:
        driver: bridge

volumes:
    db_data:
        driver: local
        driver_opts:
            type: none
            device: ${DB_DATA_PATH}
            o: bind
    web_content:
        driver: local
        driver_opts:
            type: none
            device: ${WEB_CONTENT_PATH}
            o: bind
