version: "3.8"

services:
    nginx:
        build: requirements/nginx
        image: nginx
        container_name: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        env_file:
            - .env
        volumes:
            - ${WEB_CONTENT_PATH}:/var/www/html
        networks:
            - inception
        restart:
            - always

    wordpress:
        build: requirements/wordpress
        image: imageName
        container_name: wordpress
        env_file:
            - .env
        depends_on:
            - mariadb
        volumes:
            - ${WEB_CONTENT_PATH}:/var/www/html
        networks:
            - inception
        restart:
            - always

    mariadb:
        build: requirements/mariadb
        image: mariadb
        container_name: mariadb
        env_file:
            - .env
        volumes:
            - ${DB_DATA_PATH}:/var/lib/mysql
        networks:
            - inception
        restart:
            - always
networks:
    inception:
        driver: bridge

volumes:
    db_data:
        driver: local
        driver_opts:
            type: none
            device: ${DB_DATA_PATH}
            o: bind
    web_content:
        driver: local
        driver_opts:
            type: none
            device: ${WEB_CONTENT_PATH}
            o: bind
